server:
  port: 8004
  servlet:
    context-path: /
## spring jdbc配置
spring:
  redis:
    jedis:
      pool:
        max-active: 8
        max-wait: 30
        max-idle: 8
        min-idle: 0
    host: 127.0.0.1
    password: 123456
    port: 6379
  datasource:
    url: jdbc:mysql://111.229.169.170:3306/education?serverTimezone=GMT%2B8&useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 30
      minimum-idle: 10
      max-lifetime: 6000
    ## 文件上传大小限制
    servlet:
      multipart:
        max-file-size: 200MB
        max-request-size: 200MB
# 微信公众号配置
weChat:
  appId: wx7874d0c23d07e2aa
  token: education
  appSecret: e03f5ab03906d4d943675c233d4c3cb3
## 文件上传根路径
file:
  uploadPath: E:\\uploads\\

mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.education.common.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

lbs:
  key: MYOBZ-OOEW3-KYC3G-YWDXA-DMQJ6-SPBMH

