server:
  port: 80
  servlet:
    context-path: /
## spring jdbc配置
## rootPath: /root/jar/education-admin-0.0.1-SNAPSHOT.jar!
spring:
  freemarker:
    template-loader-path: classpath:/template/
    suffix: .ftl
    charset: utf-8
  ## 文件上传大小限制
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  redis:
    jedis:
      pool:
        max-active: 8
        max-wait: 30
        max-idle: 8
        min-idle: 0
    host: 127.0.0.1
    password: 123456
    port: 6379
  main:
    allow-bean-definition-overriding: true
# shiro cookie配置
shiro:
  cookie:
    name: user_session_key
    time-out: 7200
    domain: education.gxsrkj.com
    rememberMe: true
## 虚拟文件上传路径
file:
  uploadPath: /root/uploads/
ueditor:
  configFileName: config.json
# 微信公众号配置
weChat:
  appId: wx7874d0c23d07e2aa
  token: education
  appSecret: e03f5ab03906d4d943675c233d4c3cb3
logging:
  file:  /root/jar/education.log

# sharding jdbc 读写分离配置
sharding:
  jdbc:
    datasource:
      names: education,education1
      education:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/education?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
      education1:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/education1?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
    config:
      masterslave: # 配置读写分离
        load-balance-algorithm-type: round_robin # 配置从库选择策略，提供轮询与随机，这里选择用轮询//random 随机 //round_robin 轮询
        name: db1s2
        master-data-source-name: education
        slave-data-source-names: education1
      props:
        sql:
          show: true