oss:
  upload:
    secretId: AKIDSjlW1GEvLUs3xax4tRijX4LL5XioiNmw
    secretKey: wc3D8oEPKzPZVBblfKjtnTt3xc1A3oJY
    platform: tencent
    region: ap-nanjing
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: prod
  cache:
    type: redis
  application:
    name: education
mybatis-plus:
  type-aliases-package: com.education.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mapper/**/*.xml
