host: 127.0.0.1
server:
  port: 80
## spring jdbc配置
spring:
  # flyway 数据库管理工具
  flyway:
    sql-migration-separator: _ #分隔符
    clean-disabled: true #禁用clean操作
    enabled: false #使flyway生效
    baseline-on-migrate: true #初始化时如果不存在迁移记录表，默认新建一个
    out-of-order: true #防止开发环境下漏掉没来得及apply的文件，产品环境最好设为false
    ignore-ignored-migrations: true
    locations: classpath:/db
    url: jdbc:mysql://${host}:3306/education_final?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    user: root
    password: 123456

  rabbitmq:
    host: ${host}
    port: 5672
    username: rabbitmq
    password: 123456
    virtual-host: /
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual #开启手动确认模式
    publisher-confirm-type: correlated
  redis:
    jedis:
      pool:
        max-active: 20
        max-wait: 30
        max-idle: 8
        min-idle: 0
    host: ${host}
    password: 123456
    port: 6379
  ## 文件上传大小限制
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
ueditor:
  configFileName: config-dev.json
# 微信公众号配置
weChat:
  appId: wx7874d0c23d07e2aa
  token: education
  appSecret: e03f5ab03906d4d943675c233d4c3cb3

## 文件上传根路径
file:
  uploadPath: F:\\uploads\\

# 是否开启  canal 数据同步
canal:
  openFlag: false
# sharding jdbc 读写分离配置
sharding:
  jdbc:
    datasource:
      names: educationmaster,educationslave
      educationmaster:
        maximum-pool-size: 50
          #最小空闲连接数量
        minimum-idle: 10
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://${host}:3306/education_final?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
      educationslave:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://${host}:3307/education_final?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
    config:
      masterslave: # 配置读写分离
        load-balance-algorithm-type: round_robin # 配置从库选择策略，提供轮询与随机，这里选择用轮询//random 随机 //round_robin 轮询
        name: db1s2
        master-data-source-name: educationmaster
        slave-data-source-names: educationslave
      props:
        sql:
          show: true
logging:
  file:
    path: F:\\upoads\\logs
    name: education.log