server:
  port: 8003
  servlet:
    context-path: /
## spring jdbc配置
shiro:
  cookie:
    name: user_session_key
    time-out: 7200
    domain: localhost
    rememberMe: true
spring:
  redis:
    jedis:
      pool:
        max-active: 8
        max-wait: 30
        max-idle: 8
        min-idle: 0
    host: 127.0.0.1
    password: 123456
  datasource:
    url: jdbc:mysql://111.229.169.170:3306/education?serverTimezone=GMT%2B8&useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #数据库连接超时时间
      connection-timeout: 30000
      #连接池最大连接数，默认是10
      maximum-pool-size: 30
      #最小空闲连接数量
      minimum-idle: 10
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期
      max-lifetime: 6000
    ## 文件上传大小限制
    servlet:
      multipart:
        max-file-size: 200MB
        max-request-size: 200MB
ueditor:
  configFileName: config-dev.json
# 微信公众号配置
weChat:
  appId: wx7874d0c23d07e2aa
  token: education
  appSecret: e03f5ab03906d4d943675c233d4c3cb3
## 文件上传根路径
file:
  uploadPath: E:\\uploads\\
lbs:
  key: MYOBZ-OOEW3-KYC3G-YWDXA-DMQJ6-SPBMH

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.education.common.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


